### PR TITLE
Fix unsoundness around ZSTs in slice-dst

### LINKED ISSUE #23: `alloc_slice_dst_in` may be unsound
Given the safety requirements of [`GlobalAlloc::alloc()`](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#tymethod.alloc) (and thus of `alloc::alloc`),
the following pattern looks unsound:

https://github.com/CAD97/pointer-utils/blob/a0d6f5e2e6998465a57751e3eeec8955682a29e7/crates/slice-dst/src/lib.rs#L140-L146

What if `container = |_| Layout::new::<()>()`?

### PR DESCRIPTION
**Pull request by CAD97**
This also adds `impl SliceDst for [_]` as a very simple way of observing the issue. Allocating a ZST with the global allocator is not allowed; this fixes `alloc_slice_dst_in` to handle the ZST case by returning an arbitrary aligned pointer without touching the global allocator. Fixes #23

r? @danielhenrymantilla

### CODE REVIEW

**Comment by CAD97** [comment]
Let's go ahead and make sure this passes miri on CI as well:

bors: try

**Comment by CAD97** [comment]
bors: r+

I'll publish this as slice-dst 1.1.0 and yank 1.0.0 once bors merges this.

**Comment by CAD97** [comment]
bors: r-

hold on one second, typo!

**Comment by CAD97** [comment]
bors: r+

I don't know how that random `` ` `` got there... 🙃

**Comment by danielhenrymantilla** [comment]
Half \`Layout\`, half layout, 100% typo 😄

**Pull request merged**
